import {
  ArrowRight,
  ArrowUpDown,
  ArrowRightLeft,
  BusFront,
  Check,
  ChevronDown,
  ChevronUp,
  ChevronRight,
  Clock3,
  Coffee,
  Flag,
  Footprints,
  HeartPulse,
  Info,
  Layers,
  LocateFixed,
  Map,
  MapPin,
  Menu,
  Minus,
  Navigation,
  Plus,
  Route,
  Search,
  ShoppingBag,
  Sparkles,
  Store,
  Trees,
  X,
  LoaderCircle,
  Mic,
  Square,
  QrCode,
  UserRound,
  UsersRound,
  Radio,
  LogOut,
  Power,
  WifiOff,
} from 'lucide-react';
const icons = {
  'arrow-right': ArrowRight,
  'arrow-up-down': ArrowUpDown,
  'arrow-right-left': ArrowRightLeft,
  'bus-front': BusFront,
  check: Check,
  'chevron-down': ChevronDown,
  'chevron-up': ChevronUp,
  'chevron-right': ChevronRight,
  'clock-3': Clock3,
  coffee: Coffee,
  flag: Flag,
  footprints: Footprints,
  health: HeartPulse,
  info: Info,
  layers: Layers,
  'locate-fixed': LocateFixed,
  map: Map,
  'map-pin': MapPin,
  menu: Menu,
  minus: Minus,
  navigation: Navigation,
  plus: Plus,
  route: Route,
  search: Search,
  shopping: ShoppingBag,
  sparkles: Sparkles,
  store: Store,
  trees: Trees,
  x: X,
  loading: LoaderCircle,
  mic: Mic,
  square: Square,
  qr: QrCode,
  user: UserRound,
  users: UsersRound,
  radio: Radio,
  logout: LogOut,
  power: Power,
  offline: WifiOff,
};
export function Icon({ name, className = '' }) {
  if (name === 'bus-front') return <span className={`van-icon ${className}`} aria-hidden="true" />;
  const Component = icons[name];
  return <Component className={className} strokeWidth={1.8} aria-hidden="true" />;
}
