import { useEffect, useRef, type CSSProperties } from 'react';
import { Icon } from './Icon';
import { makeLeg } from './planner';
import { scheduleLabel, stopArrivals } from './transit';
import type { Fleet } from './useFleet';
import type { Network, Route, Stop } from './types';

export function RouteExplorer({ network, selected, reversed, fleet, onSelect, onReverse, onStop, onBack, onMap }: { network: Network; selected: Route | null; reversed: boolean; fleet: Fleet; onSelect: (id: string) => void; onReverse: () => void; onStop: (stop: Stop) => void; onBack: () => void; onMap: () => void }) {
  const heading = useRef<HTMLHeadingElement>(null);
  useEffect(() => { if (selected) { heading.current?.focus({ preventScroll: true }); heading.current?.closest('#routes-panel')?.scrollIntoView({ block: 'start' }); } }, [selected?.id]);
  const ids = selected ? reversed ? [...selected.stops].reverse() : selected.stops : [];
  const leg = selected ? makeLeg(selected, reversed ? selected.stops.length - 1 : 0, reversed ? 0 : selected.stops.length - 1) : null;
  const count = (id: string) => fleet.vehicles.filter(vehicle => vehicle.routeId === id).length;
  const service = fleet.snapshot?.services.find(service => service.routeId === selected?.id);
  return <><div className="section-heading"><div><h2>Elige la ruta que quieres conocer</h2><p>Toca una tarjeta para ver de dónde sale y a dónde llega.</p></div></div><div id="route-list" hidden={!!selected}>{network.routes.map(route => <button className="route-card" style={{ '--route-color': route.color } as CSSProperties} key={route.id} onClick={() => onSelect(route.id)}>
    <span className="route-card-icon"><Icon name="bus-front" /><b>{route.id}</b></span><span><strong>{route.name}</strong><small>{network.stops.find(s => s.id === route.stops[0])!.name.replace(' · demo', '')}<br />↳ {network.stops.find(s => s.id === route.stops.at(-1))!.name.replace(' · demo', '')}</small><span className={`route-availability ${count(route.id) ? 'available' : ''}`}>{fleet.status === 'connected' ? count(route.id) ? `${count(route.id)} en servicio` : 'Sin combis activas' : 'Disponibilidad sin conexión'}</span></span><Icon name="chevron-right" /></button>)}</div>
    {selected && <><button className="secondary-button" onClick={onBack}><Icon name="arrow-right-left" />Volver a todas las rutas</button><div id="route-detail" className="route-detail" style={{ '--route-color': selected.color } as CSSProperties}><div className="selection-confirmation"><Icon name="check" />Ruta seleccionada</div><h2 ref={heading} tabIndex={-1}>Estás viendo la {selected.id}</h2><h3>{selected.name}</h3><div className="route-endpoints"><p><strong>Sale de:</strong> {network.stops.find(stop => stop.id === ids[0])!.name.replace(' · demo', '')}</p><p><strong>Llega a:</strong> {network.stops.find(stop => stop.id === ids.at(-1))!.name.replace(' · demo', '')}</p></div><div className="route-detail-title"><strong>{reversed ? 'Sentido: regreso' : 'Sentido: ida'}</strong><button className="direction-button" onClick={onReverse} disabled={!selected.bidirectional}><Icon name="arrow-right-left" />{reversed ? 'Ver ida' : 'Ver regreso'}</button></div><div className="route-facts"><span><Icon name="clock-3" />{leg!.rideMinutes} min aprox.</span><span>${selected.fare} MXN</span><span>{ids.length} paradas</span></div><button className="secondary-button route-map-button" onClick={onMap}><Icon name="map" />Ver esta ruta en el mapa</button>
      <div className="route-hours"><strong>Horario de disponibilidad</strong><p>{scheduleLabel(service?.windows ?? [])}</p><small>Hora de Lázaro Cárdenas · sujeto a choferes conectados</small></div>
      <h3>Paradas de esta ruta</h3><ol className="stop-list">{ids.map((id, i) => { const stop = network.stops.find(stop => stop.id === id)!; const next = stopArrivals(id, network, fleet.vehicles.filter(vehicle => vehicle.routeId === selected.id), fleet.now, reversed ? -1 : 1)[0]; return <li key={id}><span>{i + 1}</span><button className="stop-item" onClick={() => onStop(stop)} aria-label={`Consultar parada ${stop.name.replace(' · demo', '')}`}><div>{stop.name.replace(' · demo', '')}{i === 0 ? <small>INICIO</small> : i === ids.length - 1 ? <small>TÉRMINO</small> : null}{next && <small className="stop-next">{next.vehicle.unit} · {next.seconds < 30 ? 'llegando' : `aprox. ${Math.ceil(next.seconds / 60)} min`}</small>}</div><Icon name="chevron-right" /></button></li>; })}</ol><p className="small-note">Toca una parada para ver cuándo llega la combi. Recorrido y tarifa de ejemplo.</p></div></>}
  </>;
}
